// TODOLIST
export const GET_DATA_TODOLIST = 'GET_DATA_TODOLIST';
export const IS_LOADING_TODOLIST = 'IS_LOADING_TODOLIST';
export const PAGINATION_TODOLIST = 'PAGINATION_TODOLIST';
export const PAGINATION_DETAIL_TODOLIST = 'PAGINATION_DETAIL_TODOLIST';
export const GET_DATA_DETAIL_TODOLIST = 'GET_DATA_DETAIL_TODOLIST';
export const GET_DATA_DETAIL_OFFLINE_TODOLIST =
  'GET_DATA_DETAIL_OFFLINE_TODOLIST';
export const iS_LOADING_DETAIL_TODOLIST = 'IS_LOADING_DETAIL_TODOLIST';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_LIMIT = 'CHANGE_LIMIT';
export const CHANGE_QUERY = 'CHANGE_QUERY';

//AUTH
export const DATA_USER = 'DATA_USER';
export const IS_CONNECTED = 'IS_CONNECTED';
export const GET_TOKEN = 'GET_TOKEN';
